--- #YAML:1.0
name:               Statistics-Descriptive-Discrete
version:            0.07
abstract:           Compute descriptive statistics for discrete data sets.
author:
    - Rhet Turnbull <rhettbull@hotmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
